package com.andromega.moviepedia.movies

class DataSourceMoviesInfo {
    companion object {
        fun createDataSet(): ArrayList<NewComingMoviesModelClass> {
            val list = ArrayList<NewComingMoviesModelClass>()
            list.add(
                NewComingMoviesModelClass(
                    "Avengers",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.5",
                    "2019"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "Thor",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.6",
                    "2018"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "John Wick",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.4",
                    "2015"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "Avengers",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.4",
                    "2015"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "Avengers",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.4",
                    "2015"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "Avengers",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.4",
                    "2015"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "Avengers",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.4",
                    "2015"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "Avengers",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.4",
                    "2015"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "Avengers",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.4",
                    "2015"
                )
            )
            list.add(
                NewComingMoviesModelClass(
                    "Avengers",
                    "http://i3.ytimg.com/vi/TcMBFSGVi1c/hqdefault.jpg",
                    "7.4",
                    "2015"
                )
            )
            return list
        }
    }
}